# mvn package "-Dmaven.test.skip=true"

server:
  port: 8081

spring:
  cq:
    # 在这里配置各个功能执行顺序
    # 如果前一个功能返回 MESSAGE_BLOCK，下一个功能不会被执行
    # 如果前一个功能返回 MESSAGE_IGNORE，会继续执行下一个功能
    plugin-list:
      - ninja.skyrocketing.qqrobot.plugin.GroupMessagePlugin
      - ninja.skyrocketing.qqrobot.plugin.AdminPlugin

    # 下面配置 event 线程池，也可以删掉用默认的
    event:
      core-pool-size: 5
      max-pool-size: 20
      keep-alive-time: 2000
      work-queue-size: 512

    # 还有一些其他配置可以自己探索

reply:
  maps:
    - "equals::"

id:
  user:
    - 123456789
  group:
    - 123456789
  admin:
    - 123456789