noteandfunc:
  note: "更新日志"
  func: "可用功能"

reply:
  equalsmap:
    关键词: 类名
  containslist:
    - "关键词@类名"
  matcheslist:
    - "正则表达式@类名"
  randomlist:
    - "正则表达式@类名"

id:
  user:
    - QQ号
  group:
    - 群号
  admin:
    - QQ号
